### ISSUE TITLE
Error converting .cs file to .ts

### ISSUE THREAD

**Issue by Szotski** [madskristensen/WebEssentials2015#112]
Error when attempting to convert attached .cs file to TypeScript.

An error occurred while processing code i

n E:\Projects\CurTFS\4sight\Development\WorkInProgress2016\Product\Libs\CentralDashboardServiceShared\ResponseDataContracts\JobInstanceStatusDto.cs
System.Runtime.InteropServices.COMException (0x80004005): Unspecified error (Exception from HRESULT: 0x80004005 (E_FAIL))
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.ExternalElements.AbstractExternalCodeElement.get_ProjectItem()
   at EnvDTE.CodeClass.get_ProjectItem()
   at MadsKristensen.EditorExtensions.IntellisenseParser.ProcessElement(CodeElement element, List`1 list, HashSet`1 underProcess) in C:\projects\webessentials2015\EditorExtensions\Misc\CodeGeneration\IntellisenseParser.cs:line 89
   at MadsKristensen.EditorExtensions.IntellisenseParser.ProcessFile(ProjectItem item, HashSet`1 underProcess) in C:\projects\webessentials2015\EditorExtensions\Misc\CodeGeneration\IntellisenseParser.cs:line 49
   at MadsKristensen.EditorExtensions.ScriptIntellisenseListener.<>c__DisplayClass7_0.<ProcessAsync>b__0() in C:\projects\webessentials2015\EditorExtensions\Misc\CodeGeneration\ScriptIntellisenseListener.cs:line 58

-----Errored.cs
using System;
using System.Runtime.Serialization;

namespace CentralDashboardServiceShared.ResponseDataContracts
{
    [DataContract]
    public class JobInstanceStatusDto : ExtensibleDataObjectDtoBase
    {
        [DataMember]
        public int JobInstanceId { get; set; }

        [DataMember]
        public string Status { get; set; }

        [DataMember]
        public int JobRequestId { get; set; }

        [DataMember]
        public string JobRequestDescription { get; set; }

        [DataMember]
        public int JobDescriptionId { get; set; }

        [DataMember]
        public string JobDescription { get; set; }

        [DataMember]
        public string SiteName { get; set; }

        [DataMember]
        public string SystemName { get; set; }

        [DataMember]
        public DateTime StartTime { get; set; }

        [DataMember]
        public DateTime EndTime { get; set; }

        [DataMember]
        public string Username { get; set; }

        [DataMember]
        public bool Cancelled { get; set; }

        [DataMember]
        public string CurrentActivityName { get; set; }

        [DataMember]
        public string CurrentActivityStatus { get; set; }

        [DataMember]
        public string CurrentActivityMessage { get; set; }
    }
}

**Comment by gamer202** [comment]
Same error for dotnetcore project
