### ISSUE TITLE
Unable to generate intellisense files when base class is in another project

### ISSUE THREAD

**Issue by redwyre** [madskristensen/WebEssentials2015#116]
I'm getting this when trying to generate TypeScript or JavaScript intellisense files, which was quite confusing:

```
20/10/2015 01:09:34: An error occurred while processing code in D:\TFS\BlazingHeartWebsite\BlazingHeart.Reader\Models\Feed.cs
System.Runtime.InteropServices.COMException (0x80004005): Unspecified error (Exception from HRESULT: 0x80004005 (E_FAIL))
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.ExternalElements.AbstractExternalCodeElement.get_ProjectItem()
   at EnvDTE.CodeClass.get_ProjectItem()
   at MadsKristensen.EditorExtensions.IntellisenseParser.ProcessElement(CodeElement element, List`1 list, HashSet`1 underProcess) in C:\projects\webessentials2015\EditorExtensions\Misc\CodeGeneration\IntellisenseParser.cs:line 89
   at MadsKristensen.EditorExtensions.IntellisenseParser.ProcessFile(ProjectItem item, HashSet`1 underProcess) in C:\projects\webessentials2015\EditorExtensions\Misc\CodeGeneration\IntellisenseParser.cs:line 49
   at MadsKristensen.EditorExtensions.ScriptIntellisenseListener.<>c__DisplayClass7_0.<ProcessAsync>b__0() in C:\projects\webessentials2015\EditorExtensions\Misc\CodeGeneration\ScriptIntellisenseListener.cs:line 58

Please report this bug at https://github.com/madskristensen/WebEssentials2015/issues, and include the source of the file.
```

But then I realised the base class was in a separate project, which seems to be the issue.
I am able to reproduce it minimally with:

``` csharp
    public class DataRecordBase
    {
        public int ID { get; set; }
    }
```

in Project A, and

``` csharp
    public class Feed : DataRecordBase
    {
    }
```

In project B, referencing project A. By fiddling I can also get errors about there not being an xmldoc root element, but I think this is the underlying issue.

**Comment by videege** [comment]
I am also encountering this issue - I am unable to generate TypeScript definitions for a class with a base class in another assembly.
