### ISSUE TITLE
Nullref

### ISSUE THREAD

**Issue by zhuravlikjb** [madskristensen/WebEssentials2015#119]
See https://youtrack.jetbrains.com/issue/DEXP-68975.

```
— EXCEPTION #1/2 [NullReferenceException]
Message = “Object reference not set to an instance of an object.”
ExceptionPath = Root.InnerException
ClassName = System.NullReferenceException
HResult = COR_E_NULLREFERENCE=E_POINTER=80004003
Source = WebEssentials2015
StackTraceString = “

 at MadsKristensen.EditorExtensions.JavaScript.JsCommandFilter.Complete(Boolean force, Boolean dontAdvance) in C:\projects\webessentials2015\EditorExtensions\JavaScript\Completion\JavaScriptCompletionController.cs:line 303
 at MadsKristensen.EditorExtensions.JavaScript.JsCommandFilter.Exec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut) in C:\projects\webessentials2015\EditorExtensions\JavaScript\Completion\JavaScriptCompletionController.cs:line 204
 at Microsoft.VisualStudio.Editor.Implementation.CommandChainNode.InnerExec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
 at Microsoft.VisualStudio.Editor.Implementation.CommandChainNode.Exec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
 at JetBrains.VsIntegration.TextControl.VsTextControlOleCommandTarget.CallNextCommandTargetImpl(CommandID commandid, UInt32 cmdExecOpt, IntPtr pvaIn, IntPtr pvaOut)
 at JetBrains.VsIntegration.TextControl.VsTextControlOleCommandTarget.CallNextCommandTarget(CommandID commandid, UInt32 cmdExecOpt, IntPtr pvaIn, IntPtr pvaOut)
 at JetBrains.VsIntegration.TextControl.VsTextControlOleCommandTarget.<>c__DisplayClassa.<ExecOldCommandTarget>b__8()
 at JetBrains.DocumentModel.Impl.DocumentBase.ExpectCallbacksFromUnderlyingStore(Action F)
 at JetBrains.VsIntegration.TextControl.VsTextControlOleCommandTarget.ExecOldCommandTarget(CommandID commandid, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)

”
```

**Comment by madskristensen** [comment]
I don't have access to the YouTrack issue even when logged in. The issue has now been fixed. Thanks for the bug report :+1:

**Comment by zhuravlikjb** [comment]
Sorry, forgot to change issues visibility. Will do that for further reports. Thanks!
