### ISSUE TITLE
Index was out of range. Must be non-negative and less than the size of the collection. Parameter name: startIndex 

### ISSUE THREAD

**Issue by zhuravlikjb** [madskristensen/WebEssentials2015#120]
See https://youtrack.jetbrains.com/issue/DEXP-68976.

```
— EXCEPTION #1/2 [ArgumentOutOfRangeException]
Message = “Index was out of range. Must be non-negative and less than the size of the collection.”
ExceptionPath = Root.InnerException
ClassName = System.ArgumentOutOfRangeException
HResult = COR_E_ARGUMENTOUTOFRANGE=80131502
Source = mscorlib
ParamName = startIndex
StackTraceString = “

 at System.String.LastIndexOf(Char value, Int32 startIndex, Int32 count)
 at MadsKristensen.EditorExtensions.JavaScript.JsDocCompletionSource.GetInvocationSpan(String text, Int32 linePosition, SnapshotPoint position) in C:\projects\webessentials2015\EditorExtensions\JavaScript\Completion\JsDocCompletionSource.cs:line 25
 at MadsKristensen.EditorExtensions.JavaScript.JavaScriptCompletionSource.AugmentCompletionSession(ICompletionSession session, IList`1 completionSets) in C:\projects\webessentials2015\EditorExtensions\JavaScript\Completion\JavaScriptCompletionSourceProvider.cs:line 61
 at Microsoft.VisualStudio.Language.Intellisense.Implementation.CompletionSession.Start()
 at MadsKristensen.EditorExtensions.JavaScript.JsCommandFilter.StartSession() in C:\projects\webessentials2015\EditorExtensions\JavaScript\Completion\JavaScriptCompletionController.cs:line 365
 at MadsKristensen.EditorExtensions.JavaScript.JsCommandFilter.Exec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut) in C:\projects\webessentials2015\EditorExtensions\JavaScript\Completion\JavaScriptCompletionController.cs:line 237
 at Microsoft.VisualStudio.Editor.Implementation.CommandChainNode.InnerExec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
 at Microsoft.VisualStudio.Editor.Implementation.CommandChainNode.Exec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
 at JetBrains.VsIntegration.TextControl.VsTextControlOleCommandTarget.CallNextCommandTargetImpl(CommandID commandid, UInt32 cmdExecOpt, IntPtr pvaIn, IntPtr pvaOut)
 at JetBrains.VsIntegration.TextControl.VsTextControlOleCommandTarget.CallNextCommandTarget(CommandID commandid, UInt32 cmdExecOpt, IntPtr pvaIn, IntPtr pvaOut)
 at JetBrains.VsIntegration.TextControl.VsTextControlOleCommandTarget.<>c__DisplayClass6.<ExecDelegateBackToVs>b__5(Lifetime lifetime)
 at JetBrains.DataFlow.Lifetimes.Using(Action`1 λ)
 at JetBrains.VsIntegration.TextControl.VsTextControlOleCommandTarget.<>c__DisplayClass6.<ExecDelegateBackToVs>b__4()
 at JetBrains.Application.CommandProcessing.ICommandProcessorEx.WithCommand(ICommandProcessor thіs, String commandName, Action action)
 at JetBrains.VsIntegration.TextControl.VsTextControlOleCommandTarget.<>c__DisplayClass6.<ExecDelegateBackToVs>b__3()
 at JetBrains.DocumentModel.Impl.DocumentBase.ExpectCallbacksFromUnderlyingStore(Action F)
 at JetBrains.VsIntegration.TextControl.VsTextControlOleCommandTarget.ExecDelegateBackToVs(String sCommandName, CommandID commandid, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
 at JetBrains.VsIntegration.TextControl.VsTextControlOleCommandTarget.<>c__DisplayClass1d.<Microsoft.VisualStudio.OLE.Interop.IOleCommandTarget.Exec>b__1c(String commandName)
 at JetBrains.VsIntegration.TextControl.VsTextControlOleCommandTarget.<>c__DisplayClass19.<WithRegisteredDelegateBackToVsHandler>b__18()
 at JetBrains.Util.Logging.Logger.Catch(Action action)

”
```

**Comment by madskristensen** [comment]
I don't have access to the YouTrack issue even when logged in. The issue has now been fixed. Thanks for the bug report :+1:
