### ISSUE TITLE
System.Runtime.InteropServices.COMException (0x80004005): Error HRESULT E_FAIL has been returned from a call to a COM component

### ISSUE THREAD

**Issue by JiriZidek** [madskristensen/WebEssentials2015#149]
System.Runtime.InteropServices.COMException (0x80004005): Error HRESULT E_FAIL has been returned from a call to a COM component.
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at Microsoft.VisualStudio.LanguageServices.Implementation.Utilities.Exceptions.ThrowEFail()
   at Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.ExternalElements.AbstractExternalCodeElement.get_ProjectItem()
   at EnvDTE.CodeClass.get_ProjectItem()
   at MadsKristensen.EditorExtensions.IntellisenseParser.ProcessElement(CodeElement element, List`1 list, HashSet`1 underProcess) in C:\projects\webessentials2015\EditorExtensions\Misc\CodeGeneration\IntellisenseParser.cs:line 89
   at MadsKristensen.EditorExtensions.IntellisenseParser.ProcessFile(ProjectItem item, HashSet`1 underProcess) in C:\projects\webessentials2015\EditorExtensions\Misc\CodeGeneration\IntellisenseParser.cs:line 49
   at MadsKristensen.EditorExtensions.ScriptIntellisenseListener.<>c__DisplayClass7_0.<ProcessAsync>b__0() in C:\projects\webessentials2015\EditorExtensions\Misc\CodeGeneration\ScriptIntellisenseListener.cs:line 58
[MessagePoco.zip](https://github.com/madskristensen/WebEssentials2015/files/98159/MessagePoco.zip)

**Comment by JiriZidek** [comment]
I found, that this happens on class that is derived from class in another assembly.

Base:
```
    public class EmailAddress
    {
        public string DisplayName { get; set; }
        public string Email { get; set; }

        public override string ToString() {
            return FormatEmailAddress(DisplayName, Email);
        }

        public static string FormatEmailAddress(string displayName, string email) {
            if(string.IsNullOrWhiteSpace(displayName)) return email;
            var dn = displayName.Replace("\"", "\\\"");
            if(string.IsNullOrEmpty(email)) return dn;
            if(dn.Contains(',') || dn.Contains(';') || dn.Contains('<') || dn.Contains('>')) return $"\"{dn}\" <{email}>";
            return $"{dn} <{email}>";
        }

        public static string FormatEmailAddress(RO.Gateway g) {
            if(g == null) return null;
            return FormatEmailAddress(g.DisplayName, g.PilotAddress);
        }

        public static string FormatEmailAddress(Gateway g) {
            if(g == null) return null;
            return FormatEmailAddress(g.DisplayName, g.PilotAddress);
        }

    }
```

Derived - that should be converted to d.ts:
```
    [TypeScriptModule("Pocos")]
    public class EmailAddressPoco : EmailAddress
    {
        public int key { get; set; }            //  index
        public bool IsValid { get; set; }
    }
```

**Comment by conficient** [comment]
Getting the same error here..
