### ISSUE TITLE
Throws exception when Visual Studio 2015 launch

### ISSUE THREAD

**Issue by daviatorstorm** [madskristensen/WebEssentials2015#151]
Having a exception:
26.01.2016 16:13:59: System.Net.WebException: The remote server returned an error: (503) Server Unavailable.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MadsKristensen.EditorExtensions.JavaScript.FSPCache.<SaveUrlToFile>d__6.MoveNext() in C:\projects\webessentials2015\EditorExtensions\JavaScript\Schemas\FSPCache.cs:line 68

I have no projects directory on C drive also any projects folder on it.

**Comment by puranjayjain** [comment]
@daviatorstorm I am also facing the same problem and reported it in issue #146 and the cause is very well highlighted by you.

**Comment by daviatorstorm** [comment]
@puranjayjain  Why is it disabled?

**Comment by puranjayjain** [comment]
@daviatorstorm I think it is because of the same error that you are getting, I got that error message sometime after updating the extension to the current release.
I have tried to :
- clean install vs
- repair vs
but to no avail any ideas so as to how it maybe fixed?

**Comment by daviatorstorm** [comment]
I tried to find FSPCache.cs file to fix the problem. But without any success.
