### ISSUE TITLE
Unable to install Web Essentials 2015

### ISSUE THREAD

**Issue by litera** [madskristensen/WebEssentials2015#165]
I installed Visual Studio Enterprise 2015 (14.0.24720.00 Update 1) but when I try installing latest Web Essentials 2015 version (0.5.175) installation fails stating there's no compatible VS installed on machine. This is installation log:

```log
13. 03. 2016 16:23:25 - Microsoft VSIX Installer
13. 03. 2016 16:23:25 - -------------------------------------------
13. 03. 2016 16:23:25 - Initializing Install...
13. 03. 2016 16:23:25 - Extension Details...
13. 03. 2016 16:23:25 - 	Identifier         : 5fb7364d-2e8c-44a4-95eb-2a382e30fec9
13. 03. 2016 16:23:25 - 	Name               : Web Essentials 2015
13. 03. 2016 16:23:25 - 	Author             : Mads Kristensen
13. 03. 2016 16:23:25 - 	Version            : 0.5.175
13. 03. 2016 16:23:25 - 	Description        : Adds many useful features to Visual Studio for web developers. Requires Visual Studio 2015 RTM
13. 03. 2016 16:23:25 - 	Locale             : en-US
13. 03. 2016 16:23:25 - 	MoreInfoURL        : http://vswebessentials.com/
13. 03. 2016 16:23:25 - 	InstalledByMSI     : False
13. 03. 2016 16:23:25 - 	SupportedFrameworkVersionRange : [0.0,2147483647.2147483647]
13. 03. 2016 16:23:25 - 
13. 03. 2016 16:23:25 - 	SignatureState     : Unsigned
13. 03. 2016 16:23:25 - 	Supported Products : 
13. 03. 2016 16:23:25 - 		Microsoft.VisualStudio.Pro
13. 03. 2016 16:23:25 - 			Version : [14.0.23000,14.0.23120)
13. 03. 2016 16:23:25 - 
13. 03. 2016 16:23:25 - 	References         : 
13. 03. 2016 16:23:25 - Signature Details...
13. 03. 2016 16:23:25 - 	Extension is not signed.
13. 03. 2016 16:23:25 - 
13. 03. 2016 16:23:25 - Searching for applicable products...
13. 03. 2016 16:23:25 - Found installed product - Microsoft Visual Studio Enterprise 2015
13. 03. 2016 16:23:25 - Found installed product - Microsoft Visual Studio Professional 2015
13. 03. 2016 16:23:25 - Found installed product - Microsoft Visual Studio Community 2015
13. 03. 2016 16:23:25 - Found installed product - Microsoft Visual Studio 2015 Shell (Integrated)
13. 03. 2016 16:23:25 - Found installed product - Global Location
13. 03. 2016 16:23:25 - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.App.InitializeInstall(Boolean isRepairSupported)
   at VSIXInstaller.App.InitializeInstall()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
```

**Comment by madskristensen** [comment]
You must have an old version of Web Essentials. The latest version is 1.0.209 and can be downloaded here https://visualstudiogallery.msdn.microsoft.com/ee6e6d8c-c837-41fb-886a-6b50ae2d06a2
