### ISSUE TITLE
An error occurred while processing code AttendanceViewModel.cs to TypeScript Intellisense File

### ISSUE THREAD

**Issue by foyzulkarim** [madskristensen/WebEssentials2015#177]
4/18/2016 10:25:31 AM: An error occurred while processing code in C:\Users\foyzu\Documents\Bitbucket\schms\Projects\School\ViewModel\AttendanceViewModel.cs
System.Runtime.InteropServices.COMException (0x80004005): Error HRESULT E_FAIL has been returned from a call to a COM component.
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at Microsoft.VisualStudio.LanguageServices.Implementation.Utilities.Exceptions.ThrowEFail()
   at Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.ExternalElements.AbstractExternalCodeElement.get_ProjectItem()
   at EnvDTE.CodeClass.get_ProjectItem()
   at MadsKristensen.EditorExtensions.IntellisenseParser.ProcessElement(CodeElement element, List`1 list, HashSet`1 underProcess) in C:\projects\webessentials2015\EditorExtensions\Misc\CodeGeneration\IntellisenseParser.cs:line 89
   at MadsKristensen.EditorExtensions.IntellisenseParser.ProcessFile(ProjectItem item, HashSet`1 underProcess) in C:\projects\webessentials2015\EditorExtensions\Misc\CodeGeneration\IntellisenseParser.cs:line 49
   at MadsKristensen.EditorExtensions.ScriptIntellisenseListener.<>c__DisplayClass7_0.<ProcessAsync>b__0() in C:\projects\webessentials2015\EditorExtensions\Misc\CodeGeneration\ScriptIntellisenseListener.cs:line 58

[AttendanceViewModel.txt](https://github.com/madskristensen/WebEssentials2015/files/223075/AttendanceViewModel.txt)

**Comment by jukkahyv** [comment]
Got the same error. I installed Visual Studio 2015 Update 2 today, could that be related?
