### ISSUE TITLE
Error while generting Typescript

### ISSUE THREAD

**Issue by arunairs** [madskristensen/WebEssentials2015#224]
I am getting an error
8/31/2016 3:03:12 PM: An error occurred while processing code in c:\users\anair\documents\visual studio 2015\Projects\QComConfigurationTS\QComConfigurationTS\LoginController.cs
System.Runtime.InteropServices.COMException (0x80004005): Error HRESULT E_FAIL has been returned from a call to a COM component.
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at Microsoft.VisualStudio.LanguageServices.Implementation.Utilities.Exceptions.ThrowEFail()
   at Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.ExternalElements.AbstractExternalCodeElement.get_ProjectItem()
   at EnvDTE.CodeClass.get_ProjectItem()
   at MadsKristensen.EditorExtensions.IntellisenseParser.ProcessElement(CodeElement element, List`1 list, HashSet`1 underProcess) in C:\projects\webessentials2015\EditorExtensions\Misc\CodeGeneration\IntellisenseParser.cs:line 89
   at MadsKristensen.EditorExtensions.IntellisenseParser.ProcessFile(ProjectItem item, HashSet`1 underProcess) in C:\projects\webessentials2015\EditorExtensions\Misc\CodeGeneration\IntellisenseParser.cs:line 49
   at MadsKristensen.EditorExtensions.ScriptIntellisenseListener.<>c__DisplayClass7_0.<ProcessAsync>b__0() in C:\projects\webessentials2015\EditorExtensions\Misc\CodeGeneration\ScriptIntellisenseListener.cs:line 58

using log4net;
using System;
using System.Net;
using System.Net.Http;
using System.Web.Http;

namespace QComConfigurationTS
{
    public class LoginController : ApiController
    {
        private static readonly ILog _log = LogManager.GetLogger(typeof(LoginController));
        SecurityService _svc = new SecurityService();

        [HttpPost]
     //   [Route("api/Authentications")]
        public IHttpActionResult RegisterEmployee([FromBody] LoginDetails logindetails)
        {
            try
            {
                _log.Debug("Register Employee: " + logindetails.EmployeeId);

                return Ok(_svc.RegisterEmployee(logindetails));
            }
            catch (Exception ex)
            {
                var message = new HttpResponseMessage(HttpStatusCode.BadRequest)
                {
                    Content = new StringContent(HttpStatusCode.BadRequest.ToString())
                };
                throw new HttpResponseException(message);
            }
        }

        [HttpGet]
     //   [Route("api/Authentications/{employeeName}/{password}")]
        public IHttpActionResult ValidateEmployee(string employeeName, string password)
        {
            try
            {
                _log.DebugFormat("Validating Employee: {0}", employeeName);

                string msgValidity = _svc.ValidateEmployee(employeeName, password);
                _log.Debug("Validation Result is: " + msgValidity);
                return Ok(msgValidity);
            }
            catch (Exception ex)
            {
                var message = new HttpResponseMessage(HttpStatusCode.BadRequest)
                {
                    Content = new StringContent(HttpStatusCode.BadRequest.ToString())
                };
                throw new HttpResponseException(message);
            }
        }
    }
}

**Comment by RobSchripsema** [comment]
I am seeing exactly the same issue.
