### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by yanfelix** [madskristensen/WebEssentials2015#252]
Try to install and finally got below error report:

3/9/2017 7:09:16 PM - System.FormatException: Input string was not in a correct format.
   at System.Version.VersionResult.SetFailure(ParseFailureKind failure, String argument)
   at System.Version.TryParseComponent(String component, String componentName, VersionResult& result, Int32& parsedComponent)
   at System.Version.TryParseVersion(String version, VersionResult& result)
   at System.Version.Parse(String input)
   at System.Version..ctor(String version)
   at VSIXInstaller.SupportedVSSKU.get_VersionWithBuildRevisionInfo()
   at VSIXInstaller.App.IsValidSKUForExtension(SupportedVSSKU supportedSKU, IExtension extension, List`1 validSKUs)
   at VSIXInstaller.App.InitializeInstall(Boolean isRepairSupported)
   at VSIXInstaller.App.InitializeInstall()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

**Comment by OmerRaviv** [comment]
@yanfelix Have you by any chance installed "Visual Studio 2017 Build Tools" on your machine? Seems related: https://developercommunity.visualstudio.com/content/problem/32018/vsixinstallerexe-cant-install-extensions-when-visu.html
