### ISSUE TITLE
Angular HTML errors CompletionSession.get_CompletionSets()

### ISSUE THREAD

**Issue by thnk2wn** [madskristensen/WebEssentials2015#66]
Seeing the below error a lot in HTML files containing Angular expressions and get the feeling it's slowing down typing a little.

7/21/2015 4:43:53 PM: System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.VisualStudio.Language.Intellisense.Implementation.CompletionSession.get_CompletionSets()
   at MadsKristensen.EditorExtensions.Html.AngularLogoCompletion.<>c__DisplayClass4_0.<ChangeIcons>b__0() in C:\Users\madsk\Documents\GitHub\WebEssentials2015\EditorExtensions\HTML\Completion\AngularLogoCompletion.cs:line 35

**Comment by madskristensen** [comment]
Great, thanks for the bug report. I'll take a look

**Comment by thnk2wn** [comment]
Great, thanks!

**Comment by Dikkie** [comment]
Looks like it is still broken in 0.5.156:
27-8-2015 10:22:05: System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.VisualStudio.Language.Intellisense.Implementation.CompletionSession.get_CompletionSets()
   at MadsKristensen.EditorExtensions.Html.AngularLogoCompletion.<>c__DisplayClass4_0.<ChangeIcons>b__0() in C:\projects\webessentials2015\EditorExtensions\HTML\Completion\AngularLogoCompletion.cs:line 35
